apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: c1
    image: nginx
    ports:
    - containerports: 80
  - name: c2
    image: nginx
    ports:
    - containerPort: 80




