apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim

spec:
  StorageClassName: manual
  VolumeName: task-pv-volume
  accessmodes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 3Gi
      
